version: "3.8"

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # This tells Docker to keep node_modules in container only
      - /app/dist         # This tells Docker to keep dist in container only
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true